//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemplosDataAnotation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        [Key]
        [Required]
        [StringLength(10)]
        public int idCliente { get; set; }
        [Required]
        [StringLength(15)]
        public string nombre { get; set; }
        [Required]
        [StringLength(20)]
        public string apellido { get; set; }
        [Required]
        [StringLength(10)]
        public Nullable<int> telefono { get; set; }
        [Required]
        [StringLength(12)]
        public string estadoCli { get; set; }
       
    }
}
